version: '3.0'

services:
  grafana:
    build:
      args:
        grafana_version: ${GRAFANA_VERSION:-9.3.8}
    ports:
      - 3000:3000/tcp
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
